#This is a template for describing structure of the config file
#Set the values and add this file to .gitignore for real world projects

app:
  name: "Go-Blog"

server:
  host: "localhost"
  port: "8080"

db:
  username: "Saeed"
  password: "1234"
  host: "localhost"
  port: "3306"
  name: "go-blog"
